# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=13)),
                ('role', models.CharField(max_length=64)),
                ('interested_company', models.CharField(max_length=128)),
            ],
        ),
    ]
